spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Auto_Payment
    username: tonmoyjdbc
    password: tonmoy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
